# Resolve symlinks again at execution time before touching an existing report.
file(REAL_PATH "${JRM_BINARY_DIR}" binary)
set(ancestor "${JRM_REPORT}")
set(suffix "")
while(NOT EXISTS "${ancestor}")
    if(IS_SYMLINK "${ancestor}")
        message(FATAL_ERROR "Coverage report contains a dangling symlink: ${ancestor}")
    endif()
    get_filename_component(name "${ancestor}" NAME)
    get_filename_component(parent "${ancestor}" DIRECTORY)
    if(parent STREQUAL ancestor OR parent STREQUAL "")
        message(FATAL_ERROR "Cannot resolve coverage report directory: ${JRM_REPORT}")
    endif()
    set(suffix "${name}/${suffix}")
    set(ancestor "${parent}")
endwhile()
file(REAL_PATH "${ancestor}" resolved)
cmake_path(SET report NORMALIZE "${resolved}/${suffix}")
cmake_path(IS_PREFIX binary "${report}" NORMALIZE contained)
if(NOT contained OR report STREQUAL binary)
    message(FATAL_ERROR "Coverage report resolves outside its build directory: ${report}")
endif()
if(EXISTS "${report}")
    file(GLOB entries "${report}/*" "${report}/.*")
    if(entries AND NOT EXISTS "${report}/.jrm-coverage")
        message(FATAL_ERROR "Refusing to clear a directory not created by JRM coverage: ${report}")
    endif()
    file(REMOVE_RECURSE "${report}")
endif()
file(MAKE_DIRECTORY "${report}")
file(WRITE "${report}/.jrm-coverage" "JRM coverage report\n")
