foreach(header IN LISTS JRM_HEADERS)
    if(NOT EXISTS "${header}")
        message(FATAL_ERROR "Reflection did not generate ${header}")
    endif()
    file(SIZE "${header}" size)
    if(size EQUAL 0)
        message(FATAL_ERROR "Reflection generated an empty header: ${header}")
    endif()
endforeach()
